name: PR Labeler
on:
  pull_request:
    types: [opened]
permissions:
  contents: read

jobs:
  pr-labeler:
    permissions:
      contents: read # read config file
      pull-requests: write # add labels in PR
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@f9c084306ce8b3f488a8f3ee1ccedc6da131d1af # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
