on:
  workflow_dispatch:

jobs:
  purge-jsdelivr-cache:
    name: "Curl to purge JSDelivr cache"
    runs-on: ubuntu-latest
    steps:
      - name: "Curl"
        uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8 # v1.1
        with:
          url: https://purge.jsdelivr.net/
          method: "POST"
          accept: 200,201,204,202
          headers: '{ "cache-control": "no-cache", "content-type": "application/json" }'
          body: "{'path': ['/npm/@alma/widgets@4.x/dist/widgets.js','/npm/@alma/widgets@4.x.x/dist/widgets.js','/npm/@alma/widgets@4.x.x/dist/widgets.umd.js','/npm/@alma/widgets@4.x/dist/widgets.umd.js', '/npm/@alma/widgets@4.x.x/dist/widgets-wc.umd.js','/npm/@alma/widgets@4.x/dist/widgets-wc.umd.js','/npm/@alma/widgets@4.x.x/dist/widgets.css','/npm/@alma/widgets@4.x/dist/widgets.css','/npm/@alma/widgets@4.x.x/dist/widgets.min.css','/npm/@alma/widgets@4.x/dist/widgets.min.css']}"

          # If it is set to true, it will show the response log in the GitHub UI
          log-response: true

